spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: direct-flight-connection-service
    
# Don't add properties to this file. Any further properties will be managed in the config-server.